#!/bin/bash

python main.py --simulator=pybullet --robot=panda --num_process=1 --render=f --env=close_loop_block_pushing --num_objects=1 --max_episode_steps=50 --planner_episode=20 --device=cuda:0 --batch_size=64 --seed=0 --max_train_step=10000 --random_orientation=t --model=equi --alg=bc_con --action_sequence=pxyzr --dpos=0.05 --drot_n=4 --heightmap_size=128 --equi_n=4 --n_hidden=64 --eval_freq=-1 --num_eval_processes=0 --buffer=aug --simulate_n=0 --buffer_aug_n=4 --seed=0

python main.py --simulator=pybullet --robot=panda --num_process=1 --render=f --env=close_loop_block_pushing --num_objects=1 --max_episode_steps=50 --planner_episode=20 --device=cuda:0 --batch_size=64 --seed=0 --max_train_step=10000 --random_orientation=t --model=equi --alg=bc_con --action_sequence=pxyzr --dpos=0.05 --drot_n=4 --heightmap_size=128 --equi_n=4 --n_hidden=64 --eval_freq=-1 --num_eval_processes=0 --buffer=aug --simulate_n=0 --buffer_aug_n=4 --seed=1

python main.py --simulator=pybullet --robot=panda --num_process=1 --render=f --env=close_loop_block_pushing --num_objects=1 --max_episode_steps=50 --planner_episode=20 --device=cuda:0 --batch_size=64 --seed=0 --max_train_step=10000 --random_orientation=t --model=equi --alg=bc_con --action_sequence=pxyzr --dpos=0.05 --drot_n=4 --heightmap_size=128 --equi_n=4 --n_hidden=64 --eval_freq=-1 --num_eval_processes=0 --buffer=aug --simulate_n=0 --buffer_aug_n=4 --seed=2

python main.py --simulator=pybullet --robot=panda --num_process=1 --render=f --env=close_loop_block_pushing --num_objects=1 --max_episode_steps=50 --planner_episode=20 --device=cuda:0 --batch_size=64 --seed=0 --max_train_step=10000 --random_orientation=t --model=equi --alg=bc_con --action_sequence=pxyzr --dpos=0.05 --drot_n=4 --heightmap_size=128 --equi_n=4 --n_hidden=64 --eval_freq=-1 --num_eval_processes=0 --buffer=aug --simulate_n=0 --buffer_aug_n=4 --seed=3


python mytest.py -env=close_loop_block_in_bowl --num_obj=2 --num_processes=1 --num_eval_process=1 --render=f --max_episode_steps=100 --planner_episode=20 --dpos=0.05 --drot_n=8 --alg=bc_con --model=equi --equi_n=4 --n_hidden=64 --batch_size=64 --buffer=aug --lr=1e-3 --gamma=0.99 --seed=1 --max_train_step=10000 --simulate_n=4